version: "3"
services:
  backend:
    build: ./
    ports:
      - "3001:3001"
    working_dir: /app
    volumes:
      - ./src:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:11.1
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5
